(function(g){
'use strict';
const C=PublisherCore,R=PublisherRules;
const stats=()=>({links:0,unique:0,repeats:0,database:0,existing:0,excluded:0,titleRejected:0,screenReview:0,daRejected:0,tldRejected:0,wrongNiche:0,researched:0,ready:0,form:0,no_email:0,review:0,rejected:0,searchPages:0,languageRejected:0,contacted:0,emailDuplicate:0});
function blank(id,domain,niche){const at=new Date().toISOString();return {id,domain,website:'https://'+domain+'/',niche,query:'',discoveries:[],opportunities:[],emails:[],forms:[],contactPages:[],phones:[],socials:[],visitedURLs:[],history:[],da:null,pa:null,daSource:'',summary:'',notes:'',dealStatus:'New',reviewDecision:'auto',doNotContact:false,bucket:'no_email',score:0,scoreReasons:[],language:'unknown',languageConfidence:0,campaignId:'',campaignName:'',createdAt:at};}
function recompute(r){const d=R.decision(r);r.bucket=d.bucket;r.decisionReason=d.reason;const q=R.quality(r);r.score=q.value;r.scoreReasons=q.reasons;r.emails.sort((a,b)=>R.rank(a)-R.rank(b));const contacts=R.usableContacts(r),chosen=contacts.find(e=>e.email===r.selectedEmail);r.bestEmail=r.bucket==='rejected'?'':chosen?.email||contacts[0]?.email||'';return r;}
function mergePage(r,data,c){const now=new Date().toISOString();
 for(const found of data.emails||[]){const e=R.classifyEmail(found),old=r.emails.find(x=>x.email===e.email);if(!old)r.emails.push({...e,sources:[e.source]});else {delete old.recheckPending;old.sources=C.uniq([...(old.sources||[old.source]),e.source]);if(R.rank(e)<R.rank(old)&&old.suitability!=='excluded'){const saved={override:old.override,suppressed:old.suppressed,sources:old.sources};Object.assign(old,e,saved);}}}
 for(const key of ['phones','socials','forms','contactPages'])r[key]=C.uniq([...(r[key]||[]),...(data[key]||[])]).slice(0,key==='contactPages'?2:16);
 if(!r.summary&&data.summary){r.summary=data.summary;r.summarySource=data.url;}
 const evidence=data.pageEvidence;
 if(evidence){const assessment=R.assess(evidence,c.niche,c.subtopics,c.relatedTopics!==false);assessment.checkedAt=now;
  const found=r.opportunities.findIndex(o=>o.url===assessment.url);if(found>=0)r.opportunities[found]=assessment;else r.opportunities.push(assessment);
  // A home's/about page's actual topic evidence can clarify an offer that was otherwise ambiguous.
  if(assessment.topic.strength==='strong'&&(/\b(?:about|home)\b/i.test(assessment.role)||R.pageKey(evidence.url)===R.pageKey(r.website))){for(const o of r.opportunities)if(!o.recheckPending&&['topic_unclear','site_topic_unconfirmed'].includes(o.code)){o.topic={...assessment.topic,source:evidence.url};o.code='verified_offer';o.decision='qualified';o.reason='Publisher offer with topic evidence on '+evidence.url;}}
  r.title=r.title||assessment.title;
 }
 r.visitedURLs=C.uniq([...(r.visitedURLs||[]),R.pageKey(data.url)]);return recompute(r);
}
function tally(s,c){const rows=s.leads.filter(r=>c.researchedIds.includes(r.id));for(const key of ['ready','form','no_email','review','rejected'])c.stats[key]=rows.filter(r=>r.bucket===key).length;c.stats.researched=rows.length;return c.contactGoal==='form'?c.stats.form:c.contactGoal==='any'||c.includeForms?c.stats.ready+c.stats.form:c.stats.ready;}
function migrate(raw){const s=raw||{version:3,databases:[],leads:[],campaigns:[],settings:{sender:{},blocklist:[]},activeId:null};s.leads||=[];s.campaigns||=[];s.databases||=[];s.settings||={sender:{},blocklist:[]};s.senderProfiles||=[];
 if(s.version===3)return s;
 for(const r of s.leads){r.discoveries||=[{query:r.query||'Imported',url:r.discoveredURL||r.website,title:r.title||r.domain,at:r.createdAt}];r.opportunities||=[];r.visitedURLs||=[];r.history||=[];r.emails||=[];r.forms||=[];r.campaignId||='legacy';r.campaignName=s.campaigns.find(c=>c.id===r.campaignId)?.name||s.campaigns.find(c=>c.id===r.campaignId)?.niche||'Imported research';r.language||='unknown';if(r.bucket==='rejected'&&!r.hardReject&&!r.opportunities.length)r.hardReject={code:'legacy_rejection',reason:r.decisionReason||r.screenReason||'Excluded in previous research'};recompute(r);}
 if(s.leads.some(r=>!s.campaigns.some(c=>c.id===r.campaignId))){for(const id of [...new Set(s.leads.filter(r=>!s.campaigns.some(c=>c.id===r.campaignId)).map(r=>r.campaignId))])s.campaigns.push({id,name:'Imported research',niche:'Mixed',status:'complete',queries:[],queryStats:{},events:[],skips:[],stats:stats(),researchedIds:s.leads.filter(r=>r.campaignId===id).map(r=>r.id),createdAt:new Date().toISOString()});}
 for(const c of s.campaigns){c.name||=c.niche+' Outreach';c.stats={...stats(),...c.stats};c.checkDatabase=c.checkDatabase!==false;c.checkContacted=c.checkContacted!==false;c.researchLanguage||='any';c.requestedDA=c.requestedDA??c.requireDA;if(c.current?.record){c.current.record.campaignId=c.id;c.current.record.campaignName=c.name;}}
 if(!s.senderProfiles.length&&s.settings.sender?.email)s.senderProfiles.push({id:'default',label:'Default sender',...s.settings.sender});s.version=3;return s;
}
function restoreLead(raw,version,id){
 if(!raw||typeof raw!=='object')return null;const domain=C.domain(raw.website);if(!domain)return null;
 const short=(v,n=500)=>C.clean(v).slice(0,n),urls=(v,n=16)=>Array.isArray(v)?C.uniq(v.map(x=>C.url(x)).filter(Boolean)).slice(0,n):[],same=u=>C.domain(u)===domain;
 const stamp=v=>Number.isFinite(Date.parse(v))?new Date(v).toISOString():'',list=(v,n=200)=>Array.isArray(v)?v.filter(x=>x&&typeof x==='object').slice(0,n):[];
 const r=blank(id,domain,short(raw.niche,90));
 Object.assign(r,{website:C.url(raw.website),query:short(raw.query,300),discoveredURL:same(raw.discoveredURL)?C.url(raw.discoveredURL):r.website,title:short(raw.title,240),summary:short(raw.summary,1000),summarySource:same(raw.summarySource)?C.url(raw.summarySource):'',notes:String(raw.notes||'').slice(0,5000),dealStatus:['New','Contacted','Follow-up','Responded','Negotiating','Agreed','Not a fit'].includes(raw.dealStatus)?raw.dealStatus:'New',createdAt:stamp(raw.createdAt)||r.createdAt,collectedAt:stamp(raw.collectedAt),forms:urls(raw.forms).filter(same),contactPages:urls(raw.contactPages,2).filter(same),socials:urls(raw.socials),phones:Array.isArray(raw.phones)?raw.phones.map(x=>short(x,60)).slice(0,16):[],pagesRead:Math.max(0,Math.min(1000,Number(raw.pagesRead)||0)),stopReason:'Restored from a data backup.'});
 r.emails=list(raw.emails).filter(e=>typeof e.email==='string'&&C.emails(e.email).includes(e.email.toLowerCase())&&same(e.source)).map(e=>({...R.classifyEmail({email:e.email,source:C.url(e.source),context:short(e.context,800),pageRole:short(e.pageRole,50),attribution:e.attribution==='third_party'?'third_party':''}),sources:urls(e.sources).filter(same),override:['include','exclude'].includes(e.override)?e.override:'auto',suppressed:!!e.suppressed,contacted:!!e.contacted,databaseDuplicate:!!e.databaseDuplicate,recheckPending:!!e.recheckPending}));
 if(version>=2){
  const kinds=['Guest post','Contributor','Sponsored content','Advertising','Editorial','Contact','About'];
  r.discoveries=list(raw.discoveries,500).filter(d=>same(d.url)).map(d=>({query:short(d.query,300),url:C.url(d.url),title:short(d.title,240),snippet:short(d.snippet,700),at:stamp(d.at),screen:d.screen?{decision:['inspect','review','reject'].includes(d.screen.decision)?d.screen.decision:'review',reason:short(d.screen.reason),code:short(d.screen.code,50)}:undefined}));
  r.opportunities=list(raw.opportunities,50).filter(o=>same(o.url)).map(o=>({url:C.url(o.url),title:short(o.title,240),htmlTitle:short(o.htmlTitle,240),role:kinds.includes(o.role)?o.role:'',types:Array.isArray(o.types)?o.types.filter(t=>kinds.includes(t)):[],closedTypes:Array.isArray(o.closedTypes)?o.closedTypes.filter(t=>kinds.includes(t)):[],decision:['qualified','reject','review'].includes(o.decision)?o.decision:'review',code:short(o.code,50),reason:short(o.reason),evidence:short(o.evidence,1500),refusalEvidence:short(o.refusalEvidence,1500),recheckPending:!!o.recheckPending,checkedAt:stamp(o.checkedAt),topic:{strength:o.topic?.strength==='strong'?'strong':'weak',status:o.topic?.status==='matched'?'matched':'unclear',terms:Array.isArray(o.topic?.terms)?o.topic.terms.map(t=>short(t,100)).slice(0,10):[],source:same(o.topic?.source)?C.url(o.topic.source):''}}));
  r.history=list(raw.history,50).map(h=>({at:stamp(h.at),decision:short(h.decision,30),reason:short(h.reason),pages:Math.max(0,Number(h.pages)||0)}));r.visitedURLs=urls(raw.visitedURLs,100).filter(same);
  r.reviewDecision=['approve','reject'].includes(raw.reviewDecision)?raw.reviewDecision:'auto';r.doNotContact=!!raw.doNotContact;r.selectedEmail=r.emails.some(e=>e.email===raw.selectedEmail)?raw.selectedEmail:'';
 }
 if(!r.discoveries.length)r.discoveries=[{query:r.query||'Imported backup',url:r.discoveredURL,title:r.title,at:r.createdAt}];
 r.campaignId=short(raw.campaignId,120)||'legacy';r.campaignName=short(raw.campaignName,120)||'Imported research';r.language=/^[a-z]{2}$/.test(raw.language||'')?raw.language:'unknown';r.languageConfidence=Math.max(0,Math.min(100,Number(raw.languageConfidence)||0));if(raw.hardReject?.reason)r.hardReject={code:short(raw.hardReject.code,60),reason:short(raw.hardReject.reason,500)};r.da=Number.isInteger(raw.da)&&raw.da>=0&&raw.da<=100?raw.da:null;r.pa=Number.isInteger(raw.pa)&&raw.pa>=0&&raw.pa<=100?raw.pa:null;r.daSource=short(raw.daSource,100);if(raw.bucket==='rejected'&&!r.hardReject&&!r.opportunities.length)r.hardReject={code:'restored_rejection',reason:short(raw.decisionReason||raw.screenReason)||'Excluded in original campaign'};r.screenReason=version>=2?short(raw.screenReason):'Imported from an earlier version; recheck the opportunity';return recompute(r);
}
g.PublisherModel={blank,recompute,mergePage,tally,migrate,stats,restoreLead};
})(globalThis);
