/* Pure publisher rules, shared by worker, dashboard and tests. */
(function(g){
'use strict';
const clean=x=>String(x??'').replace(/\s+/g,' ').trim();
const uniq=a=>[...new Set(a.filter(Boolean))];
function url(x,base){try{const u=new URL(String(x).trim(),base);if(!/^https?:$/.test(u.protocol)||u.username||u.password)return '';u.hash='';return u.href;}catch{return '';}}
function domain(value){let s=clean(value);if(!s||/\s|@/.test(s))return '';if(!/^https?:\/\//i.test(s))s='https://'+s;const u=url(s);if(!u)return '';const h=new URL(u).hostname;const p=PublisherDeps.parse(h,{allowPrivateDomains:true});return !p.isIp&&(p.isIcann||p.isPrivate)?p.domain||'':'';}
function emails(text){const found=String(text||'').match(/[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9.-]*[A-Z0-9])?\.[A-Z]{2,}/gi)||[];return uniq(found.map(e=>e.toLowerCase().replace(/^[.]+|[.]+$/g,''))).filter(e=>{const [local,host]=e.split('@');return local&&local.length<65&&domain(host)&&!/(?:^|[._+-])(?:example|sample|test|yourname|youremail|emailaddress|username|noreply|no-reply|donotreply)(?:[._+-]|$)/i.test(local)&&!/(^|\.)(example\.(com|org|net)|domain\.com|yoursite\.com|yourdomain\.com|email\.com|sentry\.io|wixpress\.com|sentry-next\.wixpress\.com)$/.test(host)&&!/^.+\.(?:png|jpg|jpeg|gif|svg|webp|woff|css|js)$/i.test(e)&&!/[a-f0-9]{24,}/i.test(local);});}
const rankEmail=e=>/editor|submission|contribut|guest|publish|content/i.test(e)?0:/hello|contact|info|partnership|advertis/i.test(e)?1:/support|sales|admin/i.test(e)?3:2;
function excluded(d,blocklist=[]){if(/(?:^|\.)(?:edu|gov)(?:\.[a-z]{2})?$/.test(d)||/(?:^|\.)(?:ac\.uk|gouv\.fr|go\.jp)$/.test(d))return 'Education / government';const match=blocklist.map(domain).filter(Boolean).find(x=>d===x||d.endsWith('.'+x));return match?'Domain blocklist':'';}
const topics={health:['wellness','medicine','nutrition','fitness','mental health','healthcare'],crypto:['cryptocurrency','blockchain','bitcoin','web3','decentralized finance'],technology:['software','cybersecurity','artificial intelligence','gadgets','cloud computing'],travel:['tourism','adventure travel','destinations','hospitality'],finance:['personal finance','investing','banking','insurance'],business:['entrepreneurship','marketing','small business','management']};
function queries(niche,subtopics=''){const n=clean(niche).slice(0,90);if(!n)throw Error('Enter a niche first.');const terms=uniq([n,...(subtopics?subtopics.split(/[,\n]/).map(clean):(topics[n.toLowerCase()]||[]))]).slice(0,12);const intents=['"write for us"','"submit a guest post"','"contributor guidelines"','"guest post guidelines"','"sponsored content"','"advertise with us"'];return terms.flatMap(t=>intents.map(i=>`${t} ${i} -site:edu -site:gov`)).slice(0,48);}
function sheetLink(input){const u=new URL(input);if(u.hostname!=='docs.google.com')throw Error('Use a Google Sheets share link from docs.google.com.');const m=u.pathname.match(/^\/spreadsheets\/d\/([a-zA-Z0-9_-]+)(?:\/|$)/);if(!m||m[1]==='e')throw Error('Paste the normal Sheets share link, not a published /d/e/ link.');return {sheetId:m[1],url:`https://docs.google.com/spreadsheets/d/${m[1]}/edit`,exportURL:`https://docs.google.com/spreadsheets/d/${m[1]}/export?format=xlsx`};}
function cellDomains(value){const s=String(value||'');const matches=s.match(/https?:\/\/[^\s<>"'\])]+|(?<![@\w.-])(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}(?:\/[^\s<>"']*)?/gi)||[];return uniq(matches.map(x=>domain(x.replace(/[),;.!]+$/,''))));}
function csv(rows){const cols=['Website','Niche','Status','Emails','Contact page','Contribution page','Contribution status','Summary','Phones','Social profiles','Source query','Collected at'];const safe=x=>{const s=String(x??'');return '"'+(/^[\s]*[=+@-]/.test(s)?"'"+s:s).replace(/"/g,'""')+'"';};return '\uFEFF'+[cols,...rows.map(r=>[r.website,r.niche,r.bucket,(r.emails||[]).map(e=>e.email).join('; '),(r.contactPages||[]).slice(0,2).join('; '),r.contributionURL,r.contributionStatus,r.summary,(r.phones||[]).join('; '),(r.socials||[]).join('; '),r.query,r.collectedAt])].map(r=>r.map(safe).join(',')).join('\r\n');}
function bucket(r){return r.contributionStatus==='closed'?'review':r.emails?.length?(r.contributionStatus==='open'?'email':'review'):r.forms?.length?'form':'review';}
g.PublisherCore={clean,uniq,url,domain,emails,rankEmail,excluded,queries,sheetLink,cellDomains,csv,bucket};
})(globalThis);
