/* One saved transition per step; navigation is replayable after worker suspension. */
importScripts('vendor/publisher-deps.js','publisher-core.js','publisher-rules.js','publisher-da.js','publisher-language.js','publisher-ai.js','publisher-topics.js','publisher-model.js','publisher-sheets.js','publisher-output.js');
(function(){
'use strict';
const C=PublisherCore,R=PublisherRules,M=PublisherModel, KEY='publisherDesk', ALARM='publisher-recover';let chain=Promise.resolve(),timer;
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const defaults=()=>({version:3,senderProfiles:[],databases:[],leads:[],campaigns:[],output:{status:'Not connected',pendingIds:[],lastSyncedAt:'',error:'',endpoint:''},settings:{excludePlatforms:true,researchUnclear:false,geminiModel:'gemini-3.1-flash-lite',blocklist:['forbes.com','wikipedia.org','medium.com','reddit.com','facebook.com','linkedin.com','youtube.com','quora.com'],sender:{name:'',email:'',company:'',website:'',subject:'Guest contribution enquiry',message:''}},activeId:null});
const read=async()=>{const s=M.migrate((await chrome.storage.local.get(KEY))[KEY]||defaults());s.output ||= {status:'Not connected',pendingIds:[],lastSyncedAt:'',error:'',endpoint:''};s.output.pendingIds ||= [];return s;};
const save=s=>chrome.storage.local.set({[KEY]:s});
function queueOutput(s,id){if(!s.output?.pendingIds.includes(id))s.output.pendingIds.push(id);if(s.output?.endpoint)s.output.status='Pending';}
async function syncOutput(force=false){const s=await read(),o=s.output;if(!o.pendingIds.length)return {status:o.status,pending:0};const config=(await chrome.storage.local.get('publisherOutputConfig')).publisherOutputConfig;if(!config?.endpoint)return {status:'Not connected',pending:o.pendingIds.length};if(!force&&o.lastAttemptAt&&Date.now()-Date.parse(o.lastAttemptAt)<120000&&o.status==='Error')return {status:o.status,pending:o.pendingIds.length};const ids=o.pendingIds.slice(0,25),records=ids.map(id=>s.leads.find(r=>r.id===id)).filter(Boolean);o.lastAttemptAt=now();try{if(records.length)await PublisherOutput.send(config,'upsert',records.map(PublisherOutput.record));o.pendingIds=o.pendingIds.filter(id=>!ids.includes(id));o.status=o.pendingIds.length?'Pending':'Connected';o.lastSyncedAt=now();o.error='';}catch(e){o.status='Error';o.error=e.message;}await save(s);return {status:o.status,pending:o.pendingIds.length,error:o.error};}
const serial=fn=>{const p=chain.then(fn);chain=p.catch(()=>{});return p;};
const wake=(ms=1200)=>{clearTimeout(timer);timer=setTimeout(()=>serial(tick).catch(console.error),ms);};
const active=s=>s.campaigns.find(c=>c.id===s.activeId);
function log(c,message){c.message=message;c.events=[{at:now(),message},...(c.events||[])].slice(0,100);}
function finish(c,reason){c.status='complete';c.completedAt=now();log(c,reason);}
function publicState(s){return {...s,databases:s.databases.map(({domains,emails,contactedDomains,contactedEmails,...d})=>({...d,count:domains?.length||0,emailCount:emails?.length||0,contactedCount:contactedDomains?.length||0})),campaigns:s.campaigns.map(({seen,pending,current,serpSnapshot,...c})=>({...c,queued:pending?.length||0,current:current?{domain:current.domain,url:current.pages[0],pagesRead:current.visited.length}:null}))};}
const within=(promise,ms,label)=>{let t;return Promise.race([promise,new Promise((_,reject)=>{t=setTimeout(()=>reject(Error(label)),ms);})]).finally(()=>clearTimeout(t));};
async function navigate(c,kind,url){let tab;try{if(c[kind])tab=await chrome.tabs.get(c[kind]);}catch{}if(tab)tab=await chrome.tabs.update(tab.id,{url,active:false});else {tab=await chrome.tabs.create({url,active:false});c[kind]=tab.id;}const start=Date.now();while(Date.now()-start<11000){await sleep(450);try{tab=await chrome.tabs.get(tab.id);}catch{throw Error('Research tab was closed.');}if(tab.status==='complete')break;}await sleep(900);return tab.id;}
async function collect(tabId,method,data){await within(chrome.scripting.executeScript({target:{tabId},files:['vendor/publisher-deps.js','publisher-core.js','publisher-rules.js','publisher-da.js','publisher-collector.js']}),5000,'Page does not allow extraction.');const results=await within(chrome.scripting.executeScript({target:{tabId},func:(name,arg)=>globalThis.PublisherCollector[name](arg),args:[method,data||{}]}),5000,'Page extraction timed out.');if(!results[0]?.result)throw Error('Page returned no readable content.');return results[0].result;}
async function syncOne(db){db.status='syncing';try{const result=await PublisherSheets.fetchSheet(db.url);Object.assign(db,result,{status:'ready',lastSyncedAt:now(),error:''});}catch(e){db.status='error';db.error=e.message;throw e;}}
function contactedStatus(value){return /^(contacted|follow-up|responded|negotiating|agreed|do not contact)$/i.test(C.clean(value));}
function checkContacts(s,c,r){const other=s.leads.filter(x=>x.campaignId!==c.id&&contactedStatus(x.dealStatus));const contacted=new Set(c.checkContacted!==false?[...s.databases.flatMap(d=>d.contactedEmails||[]),...other.flatMap(x=>(x.emails||[]).map(e=>e.email))]:[]),known=new Set(c.checkDatabase!==false?s.databases.flatMap(d=>d.emails||[]):[]);for(const e of r.emails){e.contacted=contacted.has(e.email);e.databaseDuplicate=known.has(e.email);}if(r.emails.length&&r.emails.every(e=>e.contacted||e.databaseDuplicate)){r.hardReject={code:'contacted_email',reason:'Every collected email is already in the enabled database or contact history'};}}
async function aiConfig(s){return {key:(await chrome.storage.local.get('publisherGeminiKey')).publisherGeminiKey||'',model:s.settings.geminiModel||'gemini-3.1-flash-lite'};}
async function aiReview(s,c,r,data){if(!c.useGemini||c.aiDisabledReason||r.hardReject||r.aiAttempted||!data.pageEvidence?.mainText)return;const evidence=data.pageEvidence,offer=r.opportunities.find(o=>o.url===data.url);if(offer?.decision==='reject')return;if(r.score>=80)return;r.aiAttempted=true;const config=await aiConfig(s);if(!config.key){c.aiDisabledReason='Gemini key is not configured';return;}try{const result=await PublisherAI.assess(config,{niche:c.niche,topics:c.relatedTopics?c.subtopics:'',url:data.url,title:String(evidence.title||'').slice(0,240),heading:String(evidence.heading||'').slice(0,180),description:String(evidence.description||'').slice(0,400),text:evidence.mainText.slice(0,6000),emails:r.emails.slice(0,8).map(e=>({email:e.email,context:String(e.context||'').slice(0,120),kind:e.kind}))});r.aiAssessment=result;c.aiCalls=(c.aiCalls||0)+1;if(result.confidence>=80&&result.evidence){if(!result.relevant){r.hardReject={code:'ai_irrelevant',reason:result.reason||'Website does not match the campaign niche'};}if(PublisherLanguage.supported.includes(result.language)&&r.languageConfidence<85){r.language=result.language;r.languageConfidence=result.confidence;r.languageSource='Gemini with page evidence';if(PublisherLanguage.mismatch({code:r.language,confidence:r.languageConfidence},c.researchLanguage))r.hardReject={code:'language',reason:'Website language '+r.language+' does not match '+c.researchLanguage};}for(const role of result.emailRoles||[]){const e=r.emails.find(x=>x.email===role.email);if(e&&e.suitability!=='excluded'&&['Editorial','Submissions','Advertising','Partnerships','General contact'].includes(role.kind)){e.kind=role.kind;e.suitability=role.kind==='General contact'?'fallback':'recommended';e.reason='Gemini classified this published mailbox from page context';}}}M.recompute(r);}catch(e){c.aiDisabledReason=e.message;log(c,'Gemini unavailable; continuing with local scoring. '+e.message);}}
function addResults(s,c,results){
 const databases=new Set(c.checkDatabase!==false?s.databases.flatMap(d=>d.domains||[]):[]),contacted=new Set(c.checkContacted!==false?[...s.databases.flatMap(d=>d.contactedDomains||[]),...s.leads.filter(r=>r.campaignId!==c.id&&contactedStatus(r.dealStatus)).map(r=>r.domain)]:[]),seen=new Set(c.seen);
 for(const raw of results){const u=C.url(raw.url),d=C.domain(u);if(!d)continue;const query=c.queries[c.queryIndex]||'Manual URLs';const q=c.queryStats[query] ||= {pages:0,links:0,rejected:0,queued:0,ready:0};q.links++;c.stats.links++;
 const existing=s.leads.find(l=>l.domain===d&&l.campaignId===c.id),key=R.pageKey(u),discovery={query,url:u,title:C.clean(raw.title),snippet:C.clean(raw.snippet).slice(0,700),at:now()};
 if(!seen.has(d)){seen.add(d);c.stats.unique++;}else c.stats.repeats++;
 if(existing&&!existing.discoveries.some(x=>x.query===query&&R.pageKey(x.url)===key))existing.discoveries.push(discovery);
 const reason=s.leads.some(l=>l.domain===d&&l.doNotContact)?'Do not contact — saved by you':contacted.has(d)?'Website already contacted':databases.has(d)?'Already in connected databases':'';
 if(reason){if(contacted.has(d))c.stats.contacted++;else if(databases.has(d))c.stats.database++;else c.stats.existing++;c.skips.unshift({domain:d,query,url:u,title:raw.title,reason,at:now()});continue;}
 const triage=R.screen({...raw,url:u,manual:c.manual},{...s.settings,niche:c.niche,subtopics:c.subtopics,relatedTopics:c.relatedTopics,tlds:c.tlds,requireDA:c.requireDA&&!c.manual,daMin:c.daMin,daMax:c.daMax});discovery.screen=triage;
 let lead=existing;if(!lead){lead=M.blank(id(),d,c.niche);lead.campaignId=c.id;lead.campaignName=c.name;lead.query=query;lead.discoveredURL=u;lead.title=raw.title||d;lead.discoveries=[discovery];s.leads.push(lead);}lead.lastSeenAt=now();lead.screenReason=triage.reason;lead.screenCode=triage.code;lead.lastScreen=triage.decision;queueOutput(s,lead.id);if(Number.isInteger(raw.da)){lead.da=raw.da;lead.pa=Number.isInteger(raw.pa)?raw.pa:null;lead.daSource=raw.daSource||'Visible Google result metric';}
 if(triage.decision==='reject'){q.rejected++;if(['da_missing','da_range'].includes(triage.code))c.stats.daRejected++;if(triage.code==='tld')c.stats.tldRejected++;if(triage.code==='wrong_niche')c.stats.wrongNiche++;if(['platform','domain'].includes(triage.code))c.stats.excluded++;else c.stats.titleRejected++;if(!lead.visitedURLs.length&&!lead.opportunities.length){lead.bucket='rejected';lead.decisionReason=triage.reason;lead.score=0;lead.rejectionScope=['platform','domain'].includes(triage.code)?'universal':'campaign';lead.hardReject={code:triage.code,reason:triage.reason};}c.skips.unshift({domain:d,query,url:u,title:raw.title,reason:triage.reason,at:now()});continue;}
 if(triage.decision==='review'){c.stats.screenReview++;if(!lead.visitedURLs.length){lead.bucket='rejected';lead.score=0;lead.decisionReason=triage.reason;lead.hardReject={code:triage.code,reason:triage.reason};}continue;}delete lead.hardReject;
 if(lead.id!==c.recheckId&&(lead.reviewDecision==='reject'||['ready','form'].includes(lead.bucket)||lead.visitedURLs.includes(key))){c.stats.existing++;continue;}
 let pending=c.pending.find(j=>j.domain===d);if(pending){pending.extraURLs=C.uniq([...(pending.extraURLs||[]),u]);continue;}
 const upgrades=c.attempts[d]||0;if(upgrades>=2){c.stats.existing++;continue;}
 c.attempts[d]=upgrades+1;q.queued++;c.pending.push({url:u,domain:d,title:raw.title,query,leadId:lead.id,extraURLs:[]});
 }
 c.seen=[...seen];c.skips=c.skips.slice(0,1000);
}
function completeLead(s,c,reason){const j=c.current;if(!j)return;const r=j.record,saved=s.leads.find(x=>x.id===r.id);if(saved){for(const k of ['notes','dealStatus','reviewDecision','doNotContact','selectedEmail'])r[k]=saved[k];for(const e of r.emails){const old=saved.emails.find(x=>x.email===e.email);if(old){e.override=old.override;e.suppressed=old.suppressed;}}}checkContacts(s,c,r);M.recompute(r);if(r.hardReject?.code==='contacted_email')c.stats.emailDuplicate=(c.stats.emailDuplicate||0)+1;r.collectedAt=now();r.stopReason=reason;r.pagesRead=r.visitedURLs.length;r.history=[{at:now(),decision:r.bucket,reason:r.decisionReason,pages:j.visited.length},...(r.history||[])].slice(0,50);
 const i=s.leads.findIndex(x=>x.id===r.id);if(i>=0)s.leads[i]=r;else s.leads.push(r);queueOutput(s,r.id);c.researchedIds=C.uniq([...c.researchedIds,r.id]);c.current=null;const qualified=M.tally(s,c);
 for(const [query,q] of Object.entries(c.queryStats))q.ready=s.leads.filter(l=>c.researchedIds.includes(l.id)&&l.bucket==='ready'&&l.discoveries.some(d=>d.query===query)).length;
 log(c,`${r.domain}: ${reason}`);if(qualified>=c.target)finish(c,`Target reached: ${qualified} relevant websites with suitable contacts.`);
}
function createJob(s,c,r){const record=s.leads.find(l=>l.id===r.leadId)||M.blank(id(),r.domain,c.niche);record.campaignId=c.id;record.campaignName=c.name;record.incompleteReason='';return {domain:r.domain,pages:C.uniq([r.url,...(r.extraURLs||[]),record.website]),visited:[],elapsed:0,record:structuredClone(record)};}
async function tick(){const s=await read(),c=active(s);if(!c||c.status!=='running')return;try{
 if(c.phase==='sync'){
  if(c.checkDatabase===false&&c.checkContacted===false)c.syncIndex=s.databases.length;const db=s.databases[c.syncIndex];if(db){if(db.kind==='sheet'){log(c,'Checking database: '+db.name);db.status='syncing';await save(s);try{await syncOne(db);}catch(e){c.status='database_blocked';log(c,`Database unavailable: ${db.name}. ${e.message}`);await save(s);return;}}c.syncIndex++;await save(s);wake(100);return;}
  c.phase=c.manual?'research':'search';log(c,'All databases checked. Starting discovery.');
 }
 if(c.current||c.pending.length){
  c.phase='research';if(!c.current)c.current=createJob(s,c,c.pending.shift());const j=c.current;
  if(!j.pages.length||j.visited.length>=c.pageLimit||j.elapsed>=c.budget*1000){completeLead(s,c,j.elapsed>=c.budget*1000?'Research time limit reached; partial findings saved.':'Relevant pages checked.');await save(s);wake();return;}
  const next=j.pages.shift();if(j.visited.includes(next)){await save(s);wake(100);return;}j.pages.unshift(next);await save(s);const started=Date.now();let data;
  try{let tabId;if(j.resumeInPlace&&c.researchTabId){try{const tab=await chrome.tabs.get(c.researchTabId);if(C.domain(tab.url)===j.domain)tabId=tab.id;}catch{}}j.resumeInPlace=false;if(!tabId)tabId=await navigate(c,'researchTabId',next);await save(s);data=await collect(tabId,'scan');}catch(e){data={blocked:'unavailable',error:e.message};}
  j.elapsed+=Date.now()-started;
  if(data.blocked==='verification'){c.status='verification';c.verificationKind='research';log(c,'Complete verification in the research tab, then Resume, or Skip this website. Verification waiting time does not use the research budget.');await save(s);return;}
  j.pages.shift();j.visited.push(next);
  if(data.blocked){j.record.incompleteReason='Access incomplete: '+(data.error||data.blocked);completeLead(s,c,'Website unavailable: '+(data.error||'access restricted'));await save(s);wake();return;}
  if(C.domain(data.url)!==j.domain){j.record.incompleteReason='Redirected to a different domain; contact attribution needs review';completeLead(s,c,'Redirected to a different website; review required.');await save(s);wake();return;}
  const r=M.mergePage(j.record,data,c);const pageGate=R.screen({url:data.url,title:data.pageEvidence?.title},{niche:c.niche,relatedTopics:c.relatedTopics,subtopics:c.subtopics,excludePlatforms:true});if(pageGate.code==='wrong_niche')r.hardReject={code:pageGate.code,reason:pageGate.reason};const language=PublisherLanguage.detect(data.pageEvidence||{});if(language.confidence>=(r.languageConfidence||0)){r.language=language.code;r.languageConfidence=language.confidence;r.languageSource=language.source;}if(PublisherLanguage.mismatch(language,c.researchLanguage)){r.hardReject={code:'language',reason:'Website language '+language.code+' does not meet campaign language '+c.researchLanguage};c.stats.languageRejected++;}checkContacts(s,c,r);M.recompute(r);await aiReview(s,c,r,data);
  const assessment=r.opportunities.find(o=>o.url===data.url);
  const hardReject=assessment?.decision==='reject'&&['listicle','article','closed'].includes(assessment.code);
  j.pages=C.uniq([...(data.candidates||[]).map(l=>l.url),...j.pages]).filter(u=>C.domain(u)===j.domain&&!j.visited.includes(u)&&!R.platform(u)).slice(0,24);
  if(r.hardReject)completeLead(s,c,r.hardReject.reason);else if(hardReject)completeLead(s,c,assessment.reason);
  else if(r.bucket==='ready'||c.contactGoal==='form'&&r.bucket==='form'||c.contactGoal==='any'&&r.bucket==='form')completeLead(s,c,'Publisher offer, topic match and suitable contact found.');
  else if(!j.pages.length||j.visited.length>=c.pageLimit||j.elapsed>=c.budget*1000)completeLead(s,c,'Relevant page or time limit reached; all findings saved.');
 }else if(c.manual){finish(c,'All supplied websites checked.');}
 else {
  c.phase='search';if(c.queryIndex>=c.queries.length){finish(c,'All queries completed.');await save(s);return;}
  const query=c.queries[c.queryIndex];if(!c.searchURL)c.searchURL='https://www.google.com/search?q='+encodeURIComponent(query);
  log(c,`Searching query ${c.queryIndex+1}/${c.queries.length}, page ${c.pageNumber}: ${query}`);await save(s);
  let data;try{if(c.serpSnapshot)data=c.serpSnapshot;else{if(!c.searchLoaded){await navigate(c,'searchTabId',c.searchURL);c.searchLoaded=true;await save(s);}data=await collect(c.searchTabId,'search');}}catch(e){c.status='paused';log(c,'Search page could not be read: '+e.message+' Resume to retry.');c.searchLoaded=false;await save(s);return;}
  if(data.blocked){c.status=data.blocked==='verification'?'verification':'paused';c.verificationKind='search';log(c,'Google needs attention. Open the search tab, complete any verification, then Resume.');await save(s);return;}
  if(data.empty){c.status='paused';log(c,'No organic results could be read. Review the search tab for consent, an empty result page, or a layout change. Resume retries; Skip moves to the next query.');await save(s);return;}
  if(c.requireDA){let check=PublisherDA.preflight(data.results);for(let attempt=0;!check.ok&&attempt<2;attempt++){await sleep(1800);try{const later=await collect(c.searchTabId,'search');if(later.results?.length){data=later;check=PublisherDA.preflight(data.results);}}catch{break;}}if(!check.ok){c.status='da_blocked';c.serpSnapshot=data;log(c,'Moz is not connected or its DA values are unavailable. Continue without DA or stop this campaign. Your place is saved.');await save(s);return;}}
  addResults(s,c,data.results);delete c.serpSnapshot;c.stats.searchPages++;c.queryStats[query] ||= {pages:0,links:0};c.queryStats[query].pages++;
  if(data.nextURL&&c.pageNumber<c.maxPages&&!c.visitedSearch.includes(data.nextURL)){c.visitedSearch.push(c.searchURL);c.searchURL=data.nextURL;c.pageNumber++;}else {c.queryIndex++;c.pageNumber=1;c.searchURL='';c.visitedSearch=[];}c.searchLoaded=false;
 }
 await save(s);if(c.status==='running')wake(c.phase==='search'?3500:1000);
 }catch(e){c.status='paused';log(c,'Saved your progress. '+e.message);await save(s);}}
function editable(s){const c=active(s);if(c&&['running','verification','database_blocked','da_blocked','paused'].includes(c.status))throw Error('Finish or stop the active campaign before changing databases.');}
async function command(m){const s=await read(),c=m.campaignId?s.campaigns.find(x=>x.id===m.campaignId):active(s);switch(m.type){
 case 'PUB_GET':return {...publicState(s),hasKey:!!(await chrome.storage.local.get('publisherGeminiKey')).publisherGeminiKey};
 case 'PUB_ADD_DB':{editable(s);const links=C.uniq(String(m.links||'').split(/\s+/).filter(Boolean));if(!links.length||links.length>15)throw Error('Add between 1 and 15 Sheets links at a time.');const parsed=links.map(C.sheetLink);for(const p of parsed)if(!s.databases.some(d=>d.sheetId===p.sheetId))s.databases.push({id:id(),kind:'sheet',...p,name:'Google Sheet '+p.sheetId.slice(0,8),status:'new',domains:[],tabs:[]});await save(s);return true;}
 case 'PUB_SYNC_DB':{editable(s);const db=s.databases.find(d=>d.id===m.id);if(!db||db.kind!=='sheet')throw Error('Sheet not found.');try{await syncOne(db);}finally{await save(s);}return true;}
 case 'PUB_RENAME_DB':{editable(s);const db=s.databases.find(d=>d.id===m.id);if(db)db.name=C.clean(m.name).slice(0,100)||db.name;await save(s);return true;}
 case 'PUB_DELETE_DB':editable(s);s.databases=s.databases.filter(d=>d.id!==m.id);await save(s);return true;
 case 'PUB_IMPORT_DB':{editable(s);if(!Array.isArray(m.domains)||m.domains.length>500000)throw Error('Invalid database size.');const domains=C.uniq(m.domains.map(C.domain));s.databases.push({id:id(),kind:'file',name:C.clean(m.name).slice(0,120),status:'ready',domains,emails:C.uniq((m.emails||[]).flatMap(v=>C.emails(v))),contactedDomains:C.uniq((m.contactedDomains||[]).map(C.domain)),contactedEmails:C.uniq((m.contactedEmails||[]).flatMap(v=>C.emails(v))),tabs:m.tabs||[],lastSyncedAt:now()});await save(s);return domains.length;}
 case 'PUB_OUTPUT_SETTINGS':{const old=(await chrome.storage.local.get('publisherOutputConfig')).publisherOutputConfig||{},config=PublisherOutput.validateConfig({endpoint:m.endpoint,secret:m.secret||old.secret});await chrome.storage.local.set({publisherOutputConfig:config});s.output.endpoint=config.endpoint;for(const lead of s.leads)queueOutput(s,lead.id);s.output.status='Checking';s.output.error='';await save(s);try{await PublisherOutput.test(config);s.output.status='Connected';s.output.lastSyncedAt=now();}catch(e){s.output.status='Error';s.output.error=e.message;}await save(s);return {status:s.output.status+(s.output.error?' — '+s.output.error:'')};}
 case 'PUB_OUTPUT_SYNC':{const result=await syncOutput(true);return {status:result.status+(result.error?' — '+result.error:'')+', '+result.pending+' pending'};}
 case 'PUB_TOPICS':return PublisherTopics.suggest(m.niche);
 case 'PUB_AI_TEST':{const config=await aiConfig(s);if(m.key)config.key=String(m.key).trim();if(m.model)config.model=C.clean(m.model);if(!config.key)throw Error('Save a Gemini API key first.');return PublisherAI.test(config);}
 case 'PUB_OUTPUT_DISCONNECT':await chrome.storage.local.remove('publisherOutputConfig');s.output.endpoint='';s.output.status='Not connected';s.output.error='';await save(s);return true;
 case 'PUB_DA_CONTINUE':if(!c||c.status!=='da_blocked')throw Error('This campaign is not waiting for a Moz choice.');c.requireDA=false;c.daBypass=true;c.daBypassedAt=now();c.status='running';s.activeId=c.id;log(c,'Continuing without DA. Original requested range remains in the campaign report.');await save(s);wake(100);return true;
 case 'PUB_DA_TEST':{const query=C.clean(m.query).slice(0,280);if(!query)throw Error('Enter a niche or query to test MozBar.');const tab=await chrome.tabs.create({url:'https://www.google.com/search?q='+encodeURIComponent(query),active:true});let result={ok:false,reason:'MozBar metrics were not visible on this Google page.'};try{for(let attempt=0;attempt<3;attempt++){await sleep(2200);try{const data=await collect(tab.id,'search');if(data.blocked){result={ok:false,reason:'Google needs attention: '+data.blocked};break;}result=PublisherDA.preflight(data.results||[]);if(result.ok)break;}catch(e){result={ok:false,reason:e.message};}}}finally{if(result.ok)try{await chrome.tabs.remove(tab.id);}catch{}}return result;}

 case 'PUB_QUERIES':{const chosen=String(m.subtopics||'').split(/[\n,]/).map(x=>x.trim()).filter(Boolean),base=PublisherTopics.queries(m.niche,!!m.relatedTopics,chosen);if(!m.ai||!m.relatedTopics)return {queries:base,source:'Curated templates'};try{const config=await aiConfig(s);if(!config.key)throw Error('No Gemini key saved');const result=await PublisherAI.topics(config,m.niche);const terms=C.uniq([...chosen,...result.topics]).slice(0,7);return {queries:PublisherTopics.queries(m.niche,true,terms),topics:terms,source:'Gemini topic suggestions'};}catch(e){return {queries:base,source:'Curated templates — '+e.message};}}
 case 'PUB_START':{if(active(s)?.status==='running'||active(s)?.status==='verification'||active(s)?.status==='da_blocked')throw Error('Pause or stop the active campaign first.');const qs=C.uniq(String(m.queries||'').split('\n').map(C.clean).filter(q=>q.length&&q.length<300)).slice(0,60);const urls=C.uniq(String(m.urls||'').split(/\s+/).map(x=>C.url(x)).filter(u=>C.domain(u))).slice(0,1000);if(!C.clean(m.niche)||(!qs.length&&!urls.length))throw Error('Enter a niche and search queries or website URLs.');const sender=s.senderProfiles.find(p=>p.id===m.senderId),n={id:id(),name:C.clean(m.campaignName).slice(0,100)||C.clean(m.niche).slice(0,80)+' Outreach',senderId:sender?.id||'',sender:sender?structuredClone(sender):structuredClone(s.settings.sender||{}),researchLanguage:PublisherLanguage.supported.includes(m.researchLanguage)?m.researchLanguage:'any',checkDatabase:m.checkDatabase!==false,checkContacted:m.checkContacted!==false,useGemini:!!m.useGemini,requestedDA:!!m.requireDA,aiCalls:0,recheckId:m.recheckId||null,subtopics:C.clean(m.subtopics).slice(0,500),relatedTopics:!!m.relatedTopics,tlds:(Array.isArray(m.tlds)?m.tlds:[]).map(x=>String(x).toLowerCase().replace(/^\.+/,'')).filter(x=>/^[a-z]{2,20}(?:\.[a-z]{2,20})?$/.test(x)).slice(0,20),requireDA:!!m.requireDA&&!urls.length,daMin:Number(m.daMin??30),daMax:Number(m.daMax??70),contactGoal:['email','form','any'].includes(m.contactGoal)?m.contactGoal:'email',researchedIds:[],attempts:{},niche:C.clean(m.niche).slice(0,90),queries:urls.length?['Manual URLs']:qs,manual:!!urls.length,target:Math.min(5000,Math.max(1,Number(m.target)||50)),includeForms:!!m.includeForms,maxPages:Math.min(20,Math.max(1,Number(m.maxPages)||20)),budget:Math.min(180,Math.max(30,Number(m.budget)||75)),pageLimit:Math.min(10,Math.max(2,Number(m.pageLimit)||6)),status:'running',phase:'sync',syncIndex:0,queryIndex:0,pageNumber:1,searchURL:'',searchLoaded:false,visitedSearch:[],seen:[],pending:[],current:null,queryStats:{},skips:[],events:[],createdAt:now(),stats:M.stats()};
 // Manual discovery is delayed until the fresh database snapshot has loaded.
 if(n.daMin<0||n.daMax>100||n.daMin>n.daMax||!Number.isInteger(n.daMin)||!Number.isInteger(n.daMax))throw Error('Choose a valid DA range between 0 and 100.');if(m.requireDA&&urls.length)throw Error('MozBar DA filtering works on Google results; remove manual URLs or turn off DA filtering.');
 n.manualURLs=urls;s.campaigns.unshift(n);s.activeId=n.id;log(n,'Checking every database before discovery.');await save(s);await chrome.alarms.create(ALARM,{periodInMinutes:0.5});wake(100);return n.id;}
 case 'PUB_PAUSE':if(c&&c.status==='running'){c.status='paused';log(c,'Paused by you.');await save(s);}return true;
 case 'PUB_RESUME':if(c&&c.status!=='complete'){const previous=active(s);if(previous&&previous.id!==c.id&&previous.status==='running'){previous.status='paused';log(previous,'Paused while another campaign runs.');}s.activeId=c.id;if(c.status==='verification'&&c.verificationKind==='research'&&c.current)c.current.resumeInPlace=true;if(c.status==='database_blocked'){c.phase='sync';c.syncIndex=0;}c.status='running';log(c,'Continuing from saved progress.');await save(s);await chrome.alarms.create(ALARM,{periodInMinutes:0.5});wake(100);}return true;
 case 'PUB_STOP':if(c){if(c.current){const at=s.leads.findIndex(r=>r.id===c.current.record.id);if(at>=0)s.leads[at]={...c.current.record,...Object.fromEntries(['notes','dealStatus','doNotContact','reviewDecision','selectedEmail'].map(k=>[k,s.leads[at][k]]))};}c.status='stopped';c.stoppedAt=now();log(c,'Stopped. Resume this campaign to continue from the saved page and queue.');await save(s);}return true;
 case 'PUB_SKIP':if(c){if(c.current)completeLead(s,c,'Skipped by you.');else if(c.phase==='sync')throw Error('Database checks cannot be skipped. Stop the campaign to change its databases.');else {delete c.serpSnapshot;c.queryIndex++;c.pageNumber=1;c.searchURL='';c.searchLoaded=false;}if(c.status!=='complete')c.status='running';await save(s);wake(100);}return true;
 case 'PUB_OPEN_TAB':{const tabId=c?.[m.kind==='search'?'searchTabId':'researchTabId'];if(tabId){await chrome.tabs.update(tabId,{active:true});return true;}throw Error('No research tab is open yet.');}
 case 'PUB_SETTINGS':{const blocklist=C.uniq(String(m.blocklist||'').split(/[\s,]+/).map(C.domain));s.settings.blocklist=blocklist;s.settings.excludePlatforms=m.excludePlatforms!==false;s.settings.researchUnclear=!!m.researchUnclear;s.settings.aiQueries=!!m.aiQueries;s.settings.geminiModel=/^gemini-[a-z0-9.-]+$/.test(m.geminiModel||'')?m.geminiModel:s.settings.geminiModel||'gemini-3.1-flash-lite';s.settings.sender=Object.fromEntries(['name','email','company','website','subject','message'].map(k=>[k,String(m.sender?.[k]||'').slice(0,k==='message'?6000:300)]));await save(s);if(typeof m.apiKey==='string'&&m.apiKey.trim())await chrome.storage.local.set({publisherGeminiKey:m.apiKey.trim()});if(m.clearKey)await chrome.storage.local.remove('publisherGeminiKey');return true;}
 case 'PUB_SENDER_SAVE':{const email=C.emails(m.sender?.email||'')[0];if(!email)throw Error('Enter a valid sender email.');const sender={id:m.id||id(),label:C.clean(m.sender?.label).slice(0,100)||email,...Object.fromEntries(['name','company','website','subject','message'].map(k=>[k,String(m.sender?.[k]||'').slice(0,k==='message'?6000:300)])),email};const i=s.senderProfiles.findIndex(x=>x.id===sender.id);if(i<0)s.senderProfiles.push(sender);else s.senderProfiles[i]=sender;await save(s);return true;}
 case 'PUB_SENDER_DELETE':s.senderProfiles=s.senderProfiles.filter(p=>p.id!==m.id);await save(s);return true;
 case 'PUB_UPDATE_LEAD':{const r=s.leads.find(r=>r.id===m.id);if(!r)throw Error('Prospect not found.');if(typeof m.notes==='string')r.notes=m.notes.slice(0,5000);r.dealStatus=['New','Contacted','Follow-up','Responded','Negotiating','Agreed','Not a fit'].includes(m.dealStatus)?m.dealStatus:r.dealStatus;if(['auto','approve','reject'].includes(m.reviewDecision))r.reviewDecision=m.reviewDecision;if(typeof m.doNotContact==='boolean')r.doNotContact=m.doNotContact;if(typeof m.selectedEmail==='string')r.selectedEmail=m.selectedEmail;M.recompute(r);queueOutput(s,r.id);const owner=s.campaigns.find(x=>x.id===r.campaignId);if(owner)M.tally(s,owner);await save(s);return true;}
 case 'PUB_PREFILL':{const r=s.leads.find(r=>r.id===m.id);if(r?.doNotContact)throw Error('This publisher is marked do not contact.');if(!r?.forms?.length)throw Error('No supported contact form recorded.');const sender=s.campaigns.find(c=>c.id===r.campaignId)?.sender||s.settings.sender;if(!sender.email||!sender.message)throw Error('Save a sender email and message, then select that profile in the campaign.');const temp={};const tabId=await navigate(temp,'tab',r.forms[0]);await chrome.tabs.update(tabId,{active:true});const result=await collect(tabId,'prefill',sender);r.formPreparedAt=now();await save(s);return result;}
 case 'PUB_RESTORE':{editable(s);const b=m.backup;if(![1,2,3].includes(b?.version)||!Array.isArray(b.leads)||!Array.isArray(b.databases))throw Error('Choose an Outreach Desk JSON backup.');if(b.leads.length>50000||b.databases.length>100)throw Error('Backup exceeds the import limit.');let added=0;const existing=new Set(s.leads.map(r=>r.campaignId+'|'+r.domain));for(const raw of b.leads){const r=M.restoreLead(raw,b.version,id());if(!r||existing.has(r.campaignId+'|'+r.domain))continue;s.leads.push(r);existing.add(r.campaignId+'|'+r.domain);queueOutput(s,r.id);added++;}for(const cid of [...new Set(s.leads.map(r=>r.campaignId))]){if(s.campaigns.some(c=>c.id===cid))continue;const raw=(b.campaigns||[]).find(c=>c.id===cid)||{},rows=s.leads.filter(r=>r.campaignId===cid),report={id:cid,name:C.clean(raw.name||raw.niche||'Imported research').slice(0,100),niche:C.clean(raw.niche||rows[0]?.niche||'Mixed').slice(0,90),status:'complete',message:'Restored campaign report. Start a new campaign for new research.',queries:Array.isArray(raw.queries)?raw.queries.filter(v=>typeof v==='string').slice(0,60):[],queryStats:{},stats:M.stats(),researchedIds:rows.map(r=>r.id),events:[],skips:[],createdAt:raw.createdAt||now(),requireDA:!!raw.requireDA,requestedDA:!!(raw.requestedDA??raw.requireDA),daBypass:!!raw.daBypass,daMin:Number(raw.daMin)||0,daMax:Number(raw.daMax)||100,tlds:Array.isArray(raw.tlds)?raw.tlds.slice(0,20):[],researchLanguage:PublisherLanguage.supported.includes(raw.researchLanguage)?raw.researchLanguage:'any',checkDatabase:raw.checkDatabase!==false,checkContacted:raw.checkContacted!==false,subtopics:C.clean(raw.subtopics).slice(0,500),relatedTopics:!!raw.relatedTopics};M.tally(s,report);s.campaigns.push(report);}let dbAdded=0;for(const raw of b.databases){if(raw.kind==='sheet'){let p;try{p=C.sheetLink(raw.url);}catch{continue;}if(s.databases.some(d=>d.sheetId===p.sheetId))continue;s.databases.push({id:id(),kind:'sheet',...p,name:C.clean(raw.name).slice(0,100)||'Restored Sheet',status:'new',domains:[],emails:[],contactedDomains:[],contactedEmails:[],tabs:[]});dbAdded++;}else if(raw.kind==='file'&&Array.isArray(raw.domains)&&raw.domains.length<=500000){s.databases.push({id:id(),kind:'file',name:C.clean(raw.name).slice(0,100)||'Restored file',status:'ready',domains:C.uniq(raw.domains.map(C.domain)),emails:C.uniq((raw.emails||[]).flatMap(C.emails)),contactedDomains:C.uniq((raw.contactedDomains||[]).map(C.domain)),contactedEmails:C.uniq((raw.contactedEmails||[]).flatMap(C.emails)),tabs:[],lastSyncedAt:now()});dbAdded++;}}await save(s);return {added,databases:dbAdded};}
 case 'PUB_EMAIL_OVERRIDE':{const r=s.leads.find(x=>x.id===m.id),e=r?.emails.find(x=>x.email===m.email);if(!e)throw Error('Contact not found.');if(!['auto','include','exclude'].includes(m.value))throw Error('Invalid contact choice.');e.override=m.value;M.recompute(r);queueOutput(s,r.id);const owner=s.campaigns.find(x=>x.id===r.campaignId);if(owner)M.tally(s,owner);await save(s);return true;}
 case 'PUB_RECHECK':{editable(s);const r=s.leads.find(x=>x.id===m.id);if(!r)throw Error('Publisher not found.');if(r.doNotContact)throw Error('Remove the do-not-contact flag before rechecking.');const parent=s.campaigns.find(c=>c.id===r.campaignId)||{},offer=r.opportunities.find(o=>o.decision==='qualified'),u=C.url(m.url||offer?.url||r.discoveredURL||r.website);if(C.domain(u)!==r.domain)throw Error('Choose a page on this publisher’s domain.');return command({type:'PUB_START',campaignName:(parent.name||r.niche)+' · Recheck',niche:r.niche||'publishing',subtopics:parent.subtopics||'',relatedTopics:parent.relatedTopics,researchLanguage:parent.researchLanguage,senderId:parent.senderId,checkDatabase:parent.checkDatabase,checkContacted:parent.checkContacted,useGemini:parent.useGemini,urls:u,target:1,budget:90,pageLimit:8});}
 case 'PUB_BACKUP':return {...s,exportedAt:now()};
 default:throw Error('Unknown publisher action.');}}
// Populate manually supplied URLs only after all sheet refreshes succeeded.
const originalTick=tick;
tick=async function(){const s=await read(),c=active(s);if(c?.status==='running'&&c.phase==='sync'&&(c.syncIndex>=s.databases.length||c.checkDatabase===false&&c.checkContacted===false)&&c.manual&&c.manualURLs?.length){addResults(s,c,c.manualURLs.map(u=>({url:u,domain:C.domain(u),title:C.domain(u)})));c.manualURLs=[];await save(s);}return originalTick();};
chrome.runtime.onMessage.addListener((m,sender,respond)=>{if(!m?.type?.startsWith('PUB_'))return false;if(sender.id!==chrome.runtime.id||!sender.url?.startsWith(chrome.runtime.getURL('')))return false;const p=m.type==='PUB_GET'?command(m):serial(()=>command(m));p.then(value=>respond({ok:true,value}),e=>respond({ok:false,error:e.message}));return true;});
chrome.alarms.onAlarm.addListener(a=>{if(a.name===ALARM)serial(async()=>{await syncOutput();await tick();}).catch(console.error);});
chrome.runtime.onInstalled.addListener(()=>serial(async()=>{await chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true});await chrome.storage.local.setAccessLevel?.({accessLevel:'TRUSTED_CONTEXTS'});await chrome.alarms.create(ALARM,{periodInMinutes:0.5});const s=await read(),c=active(s);if(c?.status==='running'){c.status='paused';log(c,'Extension updated. Resume your saved campaign.');await save(s);}}));
chrome.runtime.onStartup.addListener(()=>serial(async()=>{await chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true});await chrome.alarms.create(ALARM,{periodInMinutes:0.5});const s=await read(),c=active(s);if(c&&!['complete','stopped'].includes(c.status)){c.status='paused';c.searchTabId=null;c.researchTabId=null;c.searchLoaded=false;log(c,'Browser restarted. Resume your campaign.');await save(s);}}));
})();
