const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const {zipSync,strToU8}=require('fflate'),{parseHTML}=require('linkedom');
const ext=path.join(__dirname,'../extension'),script=n=>fs.readFileSync(path.join(ext,n),'utf8');
function core(){const ctx=vm.createContext({URL,TextDecoder,TextEncoder,Uint8Array,AbortController,fetch,setTimeout,clearTimeout});for(const n of ['vendor/publisher-deps.js','publisher-core.js','publisher-rules.js','publisher-model.js','publisher-sheets.js'])vm.runInContext(script(n),ctx);return ctx;}
function workbook(){const files={
'xl/workbook.xml':'<workbook><sheets><sheet name="Partners" r:id="r1"/><sheet name="Hidden list" state="hidden" r:id="r2"/></sheets></workbook>',
'xl/_rels/workbook.xml.rels':'<Relationships><Relationship Id="r1" Target="worksheets/sheet1.xml"/><Relationship Id="r2" Target="worksheets/sheet2.xml"/></Relationships>',
'xl/sharedStrings.xml':'<sst><si><t>Website</t></si><si><t>https://www.alpha.co.uk/a?ref=1</t></si><si><r><t>beta.</t></r><r><t>com</t></r></si></sst>',
'xl/worksheets/sheet1.xml':'<worksheet><sheetData><row><c t="s"><v>0</v></c><c t="s"><v>1</v></c><c t="s"><v>2</v></c></row></sheetData><hyperlinks><hyperlink ref="A1" r:id="h1"/></hyperlinks></worksheet>',
'xl/worksheets/_rels/sheet1.xml.rels':'<Relationships><Relationship Id="h1" Target="https://hidden-link.org/contact" TargetMode="External"/></Relationships>',
'xl/worksheets/sheet2.xml':'<worksheet><sheetData><row><c t="inlineStr"><is><t>sub.gamma.com</t></is></c><c><f>HYPERLINK("https://formula.io","Click")</f><v>Click</v></c><c t="inlineStr"><is><t>alice@gmail.com</t></is></c></row></sheetData></worksheet>'};return zipSync(Object.fromEntries(Object.entries(files).map(([k,v])=>[k,strToU8(v)])));}
test('publisher domain keys use public suffixes and private tenant boundaries',()=>{const C=core().PublisherCore;assert.equal(C.domain('https://www.a.b.co.uk/path?q=x'),'b.co.uk');assert.equal(C.domain('https://writer.blogspot.com/post'),'writer.blogspot.com');for(const x of ['127.0.0.1','localhost','alice@gmail.com','javascript:alert(1)','https://user:pass@site.com'])assert.equal(C.domain(x),'');assert.equal(C.excluded('university.edu'),'Education / government');assert.equal(C.excluded('ministry.gov.uk'),'Education / government');assert.equal(C.excluded('forbes.com',['https://www.forbes.com']),'Domain blocklist');});
test('all workbook tabs, hidden tabs, rich strings, formulas and hyperlink targets are indexed',()=>{const r=core().PublisherSheets.xlsx(workbook());assert.equal(r.tabs.length,2);assert.equal(r.tabs[1].hidden,true);assert.deepEqual([...r.domains].sort(),['alpha.co.uk','beta.com','formula.io','gamma.com','hidden-link.org']);});
test('CSV quoted lines and email-only cells do not create duplicate domains',()=>{const r=core().PublisherSheets.csv('Website,Notes\r\n"https://blog.alpha.co.uk/path","text, notes\nmore"\r\nalice@gmail.com,"https://beta.com"');assert.deepEqual([...r.domains],['alpha.co.uk','beta.com']);assert.throws(()=>core().PublisherSheets.csv('"broken'),/unclosed/);});
test('Sheet link validation rejects published, unrelated and malformed links',()=>{const C=core().PublisherCore;assert.equal(C.sheetLink('https://docs.google.com/spreadsheets/d/abc_123/edit#gid=40').sheetId,'abc_123');assert.throws(()=>C.sheetLink('https://evil.test/spreadsheets/d/123/edit'));assert.throws(()=>C.sheetLink('https://docs.google.com/spreadsheets/d/e/abc/pubhtml'));});
test('a public workbook is downloaded anonymously; HTML auth replies fail closed',async()=>{const S=core().PublisherSheets;let options;const ok=await S.fetchSheet('https://docs.google.com/spreadsheets/d/a/edit',async(u,o)=>{options=o;return new Response(workbook());});assert.equal(ok.tabs.length,2);assert.equal(options.credentials,'omit');await assert.rejects(S.fetchSheet('https://docs.google.com/spreadsheets/d/a/edit',async()=>new Response('<html>Sign in</html>')),/did not return a workbook/);await assert.rejects(S.fetchSheet('https://docs.google.com/spreadsheets/d/a/edit',async()=>new Response('Denied',{status:403})),/403/);});
test('broken workbooks do not silently return a partial tab index',()=>{const S=core().PublisherSheets;const {unzipSync}=require('fflate');const a=unzipSync(workbook());delete a['xl/worksheets/sheet2.xml'];assert.throws(()=>S.xlsx(zipSync(a)),/missing/);a['xl/worksheets/sheet2.xml']=strToU8('<!DOCTYPE x><worksheet/>');assert.throws(()=>S.xlsx(zipSync(a)),/XML declarations/);});
test('email validation excludes placeholders and machine addresses, retains published Gmail',()=>{const C=core().PublisherCore;const r=[...C.emails('example@gmail.com yourname@real.com editor@journal.org writer.person@gmail.com no-reply@host.com a@2x.png 912384abcdabcd12341234abcdef@sentry.io')];assert.deepEqual(r,['editor@journal.org','writer.person@gmail.com']);assert.ok(C.rankEmail(r[0])<C.rankEmail(r[1]));});
test('query expansion works without AI and CSV protects spreadsheet formulas',()=>{const C=core().PublisherCore;assert.ok(C.queries('health').some(q=>q.includes('nutrition')));assert.ok(C.queries('gardening','soil,plants').some(q=>q.includes('soil')));const out=C.csv([{website:'=HYPERLINK("evil")',emails:[]}]);assert.match(out,/"'=HYPERLINK/);});
function page(html,url){const {document,window}=parseHTML(html);const ctx=core();ctx.document=document;ctx.location=new URL(url);ctx.getComputedStyle=()=>({visibility:'visible'});for(const e of document.querySelectorAll('*'))e.getClientRects=()=>[{}];ctx.HTMLInputElement=window.HTMLInputElement;ctx.HTMLTextAreaElement=window.HTMLTextAreaElement;ctx.Event=window.Event;vm.runInContext(script('publisher-collector.js'),ctx);return ctx;}
test('Google discovery reads organic results, unwraps redirects and follows the actual next link',()=>{const p=page('<html><head><title>Search</title></head><body><div id="tads"><a href="https://ad.com"><h3>Ad</h3></a></div><a href="/url?q=https%3A%2F%2Fpublisher.com%2Fwrite-for-us"><h3>Publisher</h3></a><a href="https://www.google.com/search?q=other"><h3>Google</h3></a><a id="pnnext" href="/search?q=health&amp;start=10">Next</a></body></html>','https://www.google.com/search?q=health');const r=p.PublisherCollector.search();assert.equal(r.results.length,1);assert.equal(r.results[0].domain,'publisher.com');assert.equal(r.nextURL,'https://www.google.com/search?q=health&start=10');});
test('contact research saves all usable emails and direct contribution evidence',()=>{const p=page('<html><head><title>Write for us</title><meta name="description" content="A health and nutrition journal."></head><body><h1>Write for us</h1><p>We accept guest posts about nutrition. Contact editor@journal.org and hello@journal.org. Not example@gmail.com</p><a href="/contact">Contact</a><a href="/contact-us">Contact us</a><a href="/talk">Get in touch</a></body></html>','https://journal.org/write-for-us');const r=p.PublisherCollector.scan();assert.equal(r.emails.length,2);assert.equal(r.contributionStatus,'open');assert.equal(r.contactPages.length,2);assert.equal(r.summary,'A health and nutrition journal.');});
test('closed contributions cannot qualify and embedded verification is not a whole-page block',()=>{const p=page('<html><head><title>Guidelines</title></head><body><h1>Write for us</h1><p>We are not accepting guest posts. editor@journal.org</p><div class="cf-turnstile"></div></body></html>','https://journal.org/write-for-us');const r=p.PublisherCollector.scan();assert.equal(r.contributionStatus,'closed');assert.equal(p.PublisherCore.bucket(r),'review');assert.equal(p.PublisherCollector.blocked(),'');});
test('Google challenges stop extraction before fabricated results',()=>{const p=page('<html><head><title>Unusual traffic</title></head><body><h1>Verification</h1><form action="/sorry/"></form></body></html>','https://www.google.com/sorry/');assert.equal(p.PublisherCollector.search().blocked,'verification');});
test('form preparation fills empty fields and never invokes submit or checks consent',()=>{const p=page('<html><body><form id="contact"><label for="name">Full name</label><input id="name"><input name="email" type="email"><input name="subject" value="Existing subject"><textarea name="message"></textarea><input type="checkbox" required><button type="submit">Send</button></form></body></html>','https://publisher.com/contact');let submitted=0;p.document.querySelector('form').submit=()=>submitted++;p.document.querySelector('form').addEventListener('submit',()=>submitted++);const r=p.PublisherCollector.prefill({name:'A Publisher',email:'person@sender.com',subject:'New subject',message:'Hello, editor.'});assert.equal(r.filled,3);assert.equal(p.document.querySelector('[name="subject"]').value,'Existing subject');assert.equal(submitted,0);assert.equal(p.document.querySelector('[type="checkbox"]').checked,undefined);});
module.exports={core,workbook};
test('social attribution keeps the publisher company and excludes author, share and creator links',()=>{const p=page('<html><head><title>Publisher</title></head><body><article><a href="https://linkedin.com/in/writer">Writer</a><a href="https://x.com/author">Author</a></article><footer><a href="https://www.linkedin.com/company/real-publisher/">LinkedIn</a><a href="https://facebook.com/sharer.php">Share</a><div>Designed by <a href="https://instagram.com/designer">Designer</a></div></footer></body></html>','https://publisher.com/');assert.deepEqual([...p.PublisherCollector.scan().socials],['https://www.linkedin.com/company/real-publisher']);});
test('v2 migration preserves a rejected search-only result without page evidence',()=>{const M=core().PublisherModel,r=M.blank('rejected-legacy','low-da.com','health');r.bucket='rejected';r.decisionReason='DA 12 is outside 50–90';const s=M.migrate({version:2,leads:[r],campaigns:[],databases:[],settings:{}});assert.equal(s.leads[0].bucket,'rejected');assert.equal(s.leads[0].score,0);assert.equal(s.campaigns.length,1);assert.match(s.leads[0].decisionReason,/DA 12/);});
test('restoring a search-only rejection retains its campaign and reason',()=>{const M=core().PublisherModel,r=M.blank('original','excluded.com','health');Object.assign(r,{bucket:'rejected',campaignId:'campaign-a',campaignName:'Health',decisionReason:'DA is outside this campaign range'});const restored=M.restoreLead(r,2,'restored');assert.equal(restored.bucket,'rejected');assert.equal(restored.campaignId,'campaign-a');assert.match(restored.decisionReason,/outside/);});
