const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto').webcrypto;
const root=path.join(__dirname,'../extension'),clone=structuredClone;
function env(pages={},initial={}){let stored=clone(initial),now=100000,tabNo=0,ctx;const tabs=new Map(),events={},navigation=[],timers=new Map();let timerNo=0;
 class Clock extends Date{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}static advance(ms){now+=ms;}}
 const evt=k=>({addListener:fn=>events[k]=fn});
 const chrome={sidePanel:{setPanelBehavior:async()=>{}},storage:{local:{get:async k=>({[k]:clone(stored[k])}),set:async x=>Object.assign(stored,clone(x)),remove:async k=>delete stored[k],setAccessLevel:async()=>{}}},tabs:{create:async({url})=>{const t={id:++tabNo,url,status:'complete'};tabs.set(t.id,t);navigation.push(url);return clone(t);},get:async id=>{if(!tabs.has(id))throw Error('Closed');return clone(tabs.get(id));},update:async(id,o)=>{const t=tabs.get(id);if(!t)throw Error('Closed');Object.assign(t,o);if(o.url)navigation.push(o.url);return clone(t);}},scripting:{executeScript:async r=>{if(r.files)return [];const u=tabs.get(r.target.tabId).url,p=pages[u];if(!p)throw Error('No fixture '+u);return [{result:clone(typeof p==='function'?await p({advance:ms=>now+=ms,method:r.args[0]}):p)}];}},alarms:{create:async()=>{},onAlarm:evt('alarm')},runtime:{id:'test',getURL:x=>'chrome-extension://test/'+x,onMessage:evt('message'),onStartup:evt('startup'),onInstalled:evt('installed')}};
 function boot(){ctx=vm.createContext({chrome,URL,TextDecoder,TextEncoder,Uint8Array,AbortController,AbortSignal,structuredClone,Date:Clock,crypto,console,fetch:async()=>{throw Error('Offline fixture');},setTimeout:(fn,ms)=>{timers.set(++timerNo,fn);return timerNo;},clearTimeout:n=>timers.delete(n),importScripts:()=>{}});for(const f of ['vendor/publisher-deps.js','publisher-core.js','publisher-rules.js','publisher-da.js','publisher-topics.js','publisher-model.js','publisher-language.js','publisher-ai.js','publisher-sheets.js','publisher-output.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);let source=fs.readFileSync(path.join(root,'publisher-worker.js'),'utf8').replace('sleep=ms=>new Promise(r=>setTimeout(r,ms))','sleep=async ms=>Date.advance(ms)').replace(/\}\)\(\);\s*$/,'globalThis.testing={tick:()=>tick(),command};})();');vm.runInContext(source,ctx);}boot();
 return {get ctx(){return ctx;},pages,tabs,events,navigation,restart:boot,state:()=>clone(stored.publisherDesk),campaign:()=>clone(stored.publisherDesk?.campaigns[0]),command:m=>ctx.testing.command(m),tick:()=>ctx.testing.tick(),advance:ms=>now+=ms,async done(n=100){for(let i=0;i<n;i++){await this.tick();if(this.campaign()?.status!=='running')return this.state();}throw Error('Did not finish '+JSON.stringify(this.campaign()));}};
}
const record=(url,extras={})=>({url,title:'Publisher',emails:[],forms:[],phones:[],socials:[],contactPages:[],candidates:[],summary:'A publisher',contributionStatus:'unclear',pageEvidence:{url,title:'Publisher',heading:'Publisher',mainText:'An independent health and nutrition publication.',description:''},...extras});
const good=u=>record(u,{emails:[{email:'editor@'+new URL(u).hostname,source:u,kind:'Editorial'}],contributionStatus:'open',contributionURL:u,evidence:'Write for us',pageEvidence:{url:u,title:'Write for us',heading:'Write for us',description:'Health journal',mainText:'We accept guest articles about health and nutrition. Send your article to our editorial team.'}});
const start=(e,urls,rest={})=>e.command({type:'PUB_START',niche:'health',urls,target:1,...rest});
test('manual websites are checked against every database before navigation',async()=>{const e=env({'https://fresh.com/':good('https://fresh.com/')});await e.command({type:'PUB_IMPORT_DB',name:'List one',domains:['existing.com'],tabs:[]});await e.command({type:'PUB_IMPORT_DB',name:'List two',domains:['second.com'],tabs:[]});await start(e,'https://existing.com/ https://second.com/ https://fresh.com/');await e.done();assert.deepEqual(e.navigation,['https://fresh.com/']);assert.equal(e.campaign().stats.database,2);assert.equal(e.campaign().stats.ready,1);});
test('failed Sheets refresh blocks every discovery path including manually supplied sites',async()=>{const e=env();await e.command({type:'PUB_ADD_DB',links:'https://docs.google.com/spreadsheets/d/private/edit'});await start(e,'https://fresh.com/');await e.done();assert.equal(e.campaign().status,'database_blocked');assert.equal(e.navigation.length,0);assert.equal(e.state().databases[0].status,'error');await assert.rejects(e.command({type:'PUB_SKIP'}),/cannot be skipped/);});
test('target counts unique qualified websites and early finish retains all emails',async()=>{const a='https://fresh.com/write-for-us',b='https://second.com/';const e=env({[a]:{...good(a),emails:[{email:'editor@fresh.com',source:a},{email:'hello@fresh.com',source:a}],candidates:[{url:'https://fresh.com/contact'}]},[b]:good(b)});await start(e,a+' '+a+' '+b);await e.done();assert.deepEqual(e.navigation,[a]);assert.equal(e.state().leads[0].emails.length,2);assert.equal(e.campaign().stats.ready,1);assert.equal(e.campaign().status,'complete');});
test('Google advances through actual pages, filters duplicates and stops exactly at target',async()=>{const search='https://www.google.com/search?q=health',next=search+'&start=10';const e=env({[search]:{results:[{url:'https://university.edu/',domain:'university.edu'},{url:'https://first.com/',domain:'first.com',title:'Write for us — Health'}],nextURL:next},[next]:{results:[{url:'https://first.com/article',domain:'first.com',title:'Write for us — Health'},{url:'https://second.com/',domain:'second.com',title:'Write for us — Health'}],nextURL:''},'https://first.com/':good('https://first.com/'),'https://second.com/':good('https://second.com/')});await e.command({type:'PUB_START',niche:'health',queries:'health',target:2});await e.done();assert.deepEqual(e.navigation,[search,'https://first.com/',next,'https://second.com/']);assert.equal(e.campaign().stats.repeats,1);assert.equal(e.campaign().stats.excluded,1);assert.equal(e.campaign().stats.ready,2);});
test('unavailable websites skip automatically; a challenge preserves the job for resume',async()=>{let verified=false;const a='https://blocked.com/',b='https://challenge.com/';const e=env({[a]:{blocked:'unavailable'},[b]:()=>verified?good(b):{blocked:'verification'}});await start(e,a+' '+b);await e.done();assert.equal(e.state().leads.filter(r=>r.collectedAt).length,1);assert.equal(e.campaign().status,'verification');const elapsed=e.campaign().current.elapsed;e.advance(300000);verified=true;await e.command({type:'PUB_RESUME'});await e.done();assert.equal(e.campaign().stats.ready,1);assert.equal(e.state().leads.length,2);assert.ok(elapsed<10000);});
test('page budget saves findings without resetting between pages',async()=>{const a='https://slow.com/',b=a+'contact',c=a+'about';const e=env({[a]:({advance})=>{advance(18000);return record(a,{candidates:[{url:b}]});},[b]:({advance})=>{advance(18000);return record(b,{emails:[{email:'hello@slow.com',source:b}],candidates:[{url:c}]});}});await start(e,a,{budget:30});await e.done();assert.deepEqual(e.navigation,[a,b]);assert.equal(e.state().leads[0].emails.length,1);assert.equal(e.state().leads[0].bucket,'ready');});
test('service worker restart resumes saved pending pages without double-counting',async()=>{const a='https://fresh.com/',b=a+'write-for-us';const e=env({[a]:record(a,{candidates:[{url:b}]}),[b]:good(b)});await start(e,a);await e.tick();e.restart();await e.done();assert.deepEqual(e.navigation,[a,b]);assert.equal(e.state().leads.length,1);});
test('browser restart pauses and clears stale tab IDs',async()=>{const e=env();await start(e,'https://fresh.com/');await e.events.startup();assert.equal(e.campaign().status,'paused');assert.equal(e.campaign().researchTabId,null);});
test('optional Gemini errors fall back to usable built-in queries and keys are not exported',async()=>{const e=env();await e.command({type:'PUB_SETTINGS',apiKey:'fixture-key',sender:{},blocklist:''});const q=await e.command({type:'PUB_QUERIES',niche:'health',ai:true,relatedTopics:true});assert.match(q.source,/Gemini request failed/);assert.ok(q.queries.length>0);assert.equal(JSON.stringify(await e.command({type:'PUB_BACKUP'})).includes('fixture-key'),false);assert.equal(JSON.stringify(await e.command({type:'PUB_GET'})).includes('fixture-key'),false);});
test('form-only target mode is explicit and closed submission pages are rejected',async()=>{const a='https://forms.com/',b='https://closed.com/';const e=env({[a]:{...good(a),emails:[],forms:[a+'contact']},[b]:{...good(b),contributionStatus:'closed',pageEvidence:{url:b,title:'Write for us',heading:'Write for us',mainText:'We do not accept guest posts on health.'}}});await start(e,b+' '+a,{includeForms:true});await e.done();assert.equal(e.campaign().stats.form,1);assert.equal(e.campaign().stats.rejected,1);assert.equal(e.campaign().stats.ready,0);});
test('restoring a backup merges new prospects, preserves notes and does not restart campaigns',async()=>{const a='https://fresh.com/';const e=env({[a]:good(a)});await start(e,a);await e.done();const lead=e.state().leads[0];await e.command({type:'PUB_UPDATE_LEAD',id:lead.id,notes:'Agreed rate, awaiting reply.',dealStatus:'Negotiating'});const backup=await e.command({type:'PUB_BACKUP'}),restored=env();const r=await restored.command({type:'PUB_RESTORE',backup});assert.equal(r.added,1);assert.equal(restored.state().leads[0].notes,'Agreed rate, awaiting reply.');assert.equal(restored.state().leads[0].dealStatus,'Negotiating');assert.equal(restored.state().campaigns.length,1);assert.equal((await restored.command({type:'PUB_RESTORE',backup})).added,0);});
test('resume after a publisher verification reads the same tab without reloading',async()=>{let verified=false;const a='https://verify.com/';const e=env({[a]:()=>verified?good(a):{blocked:'verification'}});await start(e,a);await e.done();verified=true;await e.command({type:'PUB_RESUME'});await e.done();assert.equal(e.navigation.length,1);assert.equal(e.campaign().stats.ready,1);});
test('stop saves partial contacts already found on the active website',async()=>{const a='https://partial.com/';const e=env({[a]:record(a,{emails:[{email:'hello@partial.com',source:a}],candidates:[{url:a+'contact'}]})});await start(e,a);await e.tick();await e.command({type:'PUB_STOP'});assert.equal(e.campaign().status,'stopped');assert.equal(e.state().leads[0].emails[0].email,'hello@partial.com');});

module.exports={env,record,good,start};
test('list title is skipped before navigation and a later valid page upgrades the same domain',async()=>{const a='https://journal.com/top-100',b='https://journal.com/write-for-us',q1='health guest posts',q2='health contribute',s1='https://www.google.com/search?q='+encodeURIComponent(q1),s2='https://www.google.com/search?q='+encodeURIComponent(q2);const e=env({[s1]:{results:[{url:a,title:'Top 100 Websites That Accept Guest Posts'}]},[s2]:{results:[{url:b,title:'Write for Us — Health'}]},[b]:good(b)});await e.command({type:'PUB_START',niche:'health',queries:q1+'\n'+q2,target:1});await e.done();assert.deepEqual(e.navigation,[s1,s2,b]);assert.equal(e.state().leads.length,1);assert.deepEqual(e.state().leads[0].discoveries.map(d=>d.query),[q1,q2]);assert.equal(e.state().leads[0].bucket,'ready');assert.equal(e.campaign().stats.titleRejected,1);});
test('first-party support contact remains usable with a lower quality score',async()=>{const a='https://support-only.com/',b='https://good-contact.com/';const e=env({[a]:{...good(a),emails:[{email:'support@support-only.com',source:a}]},[b]:good(b)});await start(e,a+' '+b,{target:2});await e.done();const [support,editorial]=e.state().leads;assert.equal(support.bucket,'ready');assert.equal(support.emails[0].kind,'Customer support');assert.ok(support.score<editorial.score);assert.equal(e.campaign().stats.ready,2);});
test('notes and do-not-contact decisions survive an in-progress job',async()=>{const a='https://in-progress.com/',b=a+'contribute';const e=env({[a]:record(a,{candidates:[{url:b}]}),[b]:good(b)});await start(e,a);await e.tick();const r=e.state().leads[0];await e.command({type:'PUB_UPDATE_LEAD',id:r.id,notes:'Keep this note.',doNotContact:true});await e.done();assert.equal(e.state().leads[0].notes,'Keep this note.');assert.equal(e.state().leads[0].doNotContact,true);assert.equal(e.state().leads[0].bucket,'rejected');assert.equal(e.campaign().stats.ready,0);});
test('v2 backup retains evidence, keywords, history and manual email choices',async()=>{const a='https://restore-rich.com/';const e=env({[a]:good(a)});await start(e,a);await e.done();const r=e.state().leads[0];await e.command({type:'PUB_EMAIL_OVERRIDE',id:r.id,email:r.emails[0].email,value:'exclude'});await e.command({type:'PUB_UPDATE_LEAD',id:r.id,reviewDecision:'approve',doNotContact:true});const restored=env();await restored.command({type:'PUB_RESTORE',backup:await e.command({type:'PUB_BACKUP'})});const saved=restored.state().leads[0];assert.equal(saved.emails[0].override,'exclude');assert.equal(saved.reviewDecision,'approve');assert.equal(saved.doNotContact,true);assert.equal(saved.opportunities[0].decision,'qualified');assert.equal(saved.discoveries[0].query,'Manual URLs');assert.equal(saved.history.length,1);});
test('recheck creates a separate report without mutating the original contacts or decisions',async()=>{const a='https://recheck.com/',b=a+'write-for-us';const e=env({[a]:record(a,{candidates:[{url:b}]}),[b]:good(b)});await start(e,a);await e.done();const r=e.state().leads[0];await e.command({type:'PUB_UPDATE_LEAD',id:r.id,reviewDecision:'approve',notes:'A preferred publisher'});e.pages[b]={...good(b),emails:[]};e.pages[a]=record(a);await e.command({type:'PUB_RECHECK',id:r.id});await e.done();const [original,rechecked]=e.state().leads;assert.equal(e.navigation[2],b);assert.equal(original.reviewDecision,'approve');assert.equal(original.notes,'A preferred publisher');assert.equal(original.bucket,'ready');assert.equal(rechecked.emails.length,0);assert.equal(rechecked.bucket,'no_email');assert.notEqual(original.campaignId,rechecked.campaignId);assert.equal(e.state().campaigns.length,2);});

test('DA preflight blocks research when MozBar metrics are missing',async()=>{const q='education write for us',search='https://www.google.com/search?q='+encodeURIComponent(q),e=env({[search]:{results:[{url:'https://example.com/write-for-us',title:'Education — Write for us'}]}});await e.command({type:'PUB_START',niche:'Education',queries:q,requireDA:true,daMin:30,daMax:70,target:1});await e.done();assert.equal(e.campaign().status,'da_blocked');assert.deepEqual(e.navigation,[search]);assert.equal(e.campaign().stats.researched,0);});
test('DA range and TLD reject before publisher navigation',async()=>{const q='education guest post',search='https://www.google.com/search?q='+encodeURIComponent(q),e=env({[search]:{results:[{url:'https://good.com/write-for-us',title:'Education — Write for us',da:45,pa:20,daSource:'Visible Google result metric'},{url:'https://low.com/write-for-us',title:'Education — Write for us',da:7,pa:10,daSource:'Visible Google result metric'},{url:'https://other.pk/write-for-us',title:'Education — Write for us',da:51,pa:20,daSource:'Visible Google result metric'}]},'https://good.com/write-for-us':good('https://good.com/write-for-us')});await e.command({type:'PUB_START',niche:'Education',queries:q,tlds:['com'],requireDA:true,daMin:30,daMax:70,target:1});await e.done();assert.equal(e.campaign().stats.daRejected,1);assert.equal(e.campaign().stats.tldRejected,1);assert.ok(e.navigation.includes('https://good.com/write-for-us'));assert.ok(!e.navigation.some(u=>/low\.com|other\.pk/.test(u)));});
test('output connection errors preserve pending publisher rows and never export the secret in backups',async()=>{const u='https://fresh.com/';const e=env({[u]:good(u)});await start(e,u);await e.done();const secret='abcdefghijklmnopABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-';const result=await e.command({type:'PUB_OUTPUT_SETTINGS',endpoint:'https://script.google.com/macros/s/deployment_test-123/exec',secret});assert.match(result.status,/Error/);assert.equal(e.state().output.pendingIds.length,1);assert.equal(JSON.stringify(await e.command({type:'PUB_BACKUP'})).includes(secret),false);const sync=await e.command({type:'PUB_OUTPUT_SYNC'});assert.match(sync.status,/Error/);assert.equal(e.state().output.pendingIds.length,1);});
test('same domain keeps separate campaign DA requirements and results',async()=>{const q='health write for us',search='https://www.google.com/search?q='+encodeURIComponent(q),url='https://isolated.com/write-for-us',e=env({[search]:{results:[{url,title:'Health Write for us',da:45,pa:32,daSource:'Visible Google result metric'},{url:'https://university.edu/',title:'Write for us',da:60,pa:40,daSource:'Visible Google result metric'}],nextURL:''},[url]:good(url)});await e.command({type:'PUB_START',campaignName:'Health strict',niche:'health',queries:q,requireDA:true,daMin:50,daMax:90,target:1});await e.done();await e.command({type:'PUB_START',campaignName:'Health broad',niche:'health',queries:q,requireDA:true,daMin:20,daMax:50,target:1});await e.done();const rows=e.state().leads.filter(r=>r.domain==='isolated.com');assert.equal(rows.length,2);assert.equal(rows[0].bucket,'rejected');assert.equal(rows[1].bucket,'ready');assert.notEqual(rows[0].campaignId,rows[1].campaignId);assert.equal(e.state().campaigns[1].daMin,50);assert.equal(e.state().campaigns[0].daMin,20);});
test('Moz fallback saves the current results and stop-resume does not restart the search',async()=>{const q='health write for us',search='https://www.google.com/search?q='+encodeURIComponent(q),url='https://moz-fallback.com/write-for-us',e=env({[search]:{results:[{url,title:'Health Write for us'}],nextURL:''},[url]:good(url)});await e.command({type:'PUB_START',niche:'health',queries:q,requireDA:true,daMin:50,daMax:90,target:1});await e.done();assert.equal(e.campaign().status,'da_blocked');const snapshot=e.campaign().serpSnapshot;await e.command({type:'PUB_STOP'});assert.deepEqual(e.campaign().serpSnapshot,snapshot);await e.command({type:'PUB_RESUME'});await e.done();assert.equal(e.campaign().status,'da_blocked');await e.command({type:'PUB_DA_CONTINUE'});await e.done();assert.deepEqual(e.navigation,[search,url]);assert.equal(e.campaign().daBypass,true);assert.equal(e.campaign().requestedDA,true);assert.equal(e.campaign().daMin,50);assert.equal(e.campaign().stats.ready,1);});
test('stopping mid-research retains the exact remaining page and resumes it',async()=>{const a='https://resume-site.com/',b=a+'contact',e=env({[a]:record(a,{candidates:[{url:b}]}),[b]:good(b)});await start(e,a);await e.tick();const remaining=e.campaign().current.pages;await e.command({type:'PUB_STOP'});assert.deepEqual(e.campaign().current.pages,remaining);await e.command({type:'PUB_RESUME'});await e.done();assert.deepEqual(e.navigation,[a,b]);assert.equal(e.campaign().stats.ready,1);});
test('database and contacted checks can be disabled independently for a campaign',async()=>{const a='https://known.com/',e=env({[a]:good(a)});await e.command({type:'PUB_IMPORT_DB',name:'Existing',domains:['known.com'],emails:['editor@known.com'],contactedDomains:['known.com'],contactedEmails:['editor@known.com']});await start(e,a,{checkDatabase:false,checkContacted:true});await e.done();assert.equal(e.campaign().stats.contacted,1);assert.equal(e.navigation.length,0);await start(e,a,{checkDatabase:false,checkContacted:false});await e.done();assert.equal(e.campaign().stats.ready,1);});
test('already contacted email is rejected even on a newly discovered domain',async()=>{const a='https://new-host.com/',e=env({[a]:{...good(a),emails:[{email:'editor@old-host.com',source:a}]}});await e.command({type:'PUB_IMPORT_DB',name:'History',domains:['old-host.com'],emails:[],contactedEmails:['editor@old-host.com']});await start(e,a,{checkDatabase:false,checkContacted:true});await e.done();assert.equal(e.state().leads[0].bucket,'rejected');assert.equal(e.state().leads[0].bestEmail,'');assert.equal(e.campaign().stats.emailDuplicate,1);});
test('campaign language rejects declared Spanish and keeps unknown-language contacts',async()=>{const a='https://spanish.com/',b='https://unknown-language.com/',e=env({[a]:{...good(a),pageEvidence:{url:a,title:'Write for us',heading:'Write for us',mainText:'We accept guest articles about health.',declaredLanguage:'es'}},[b]:good(b)});await start(e,a+' '+b,{researchLanguage:'en'});await e.done();assert.equal(e.state().leads[0].hardReject.code,'language');assert.equal(e.state().leads[1].bucket,'ready');assert.equal(e.campaign().stats.languageRejected,1);});
test('sender profile is captured per campaign and Gemini key can be tested and cleared',async()=>{const e=env();await e.command({type:'PUB_SENDER_SAVE',sender:{label:'Editorial',name:'Sam',email:'sam@outreach-team.com'}});const sender=e.state().senderProfiles[0];await start(e,'https://fresh.com/',{senderId:sender.id});assert.equal(e.campaign().sender.email,sender.email);await e.command({type:'PUB_SENDER_SAVE',id:sender.id,sender:{label:'Updated',email:'new@outreach-team.com'}});assert.equal(e.campaign().sender.email,'sam@outreach-team.com');await e.command({type:'PUB_SETTINGS',apiKey:'fixture-key',sender:{},blocklist:''});assert.equal((await e.command({type:'PUB_GET'})).hasKey,true);await e.command({type:'PUB_SETTINGS',clearKey:true,sender:{},blocklist:''});assert.equal((await e.command({type:'PUB_GET'})).hasKey,false);});
